server:
    port: 8888

spring:
    application:
        name: config
    cloud:
        config:
            label: master
            server:
                git:
                    uri: https://github.com/WakelessDragon/config
                    searchPaths: architecure
                    username:
                    password:

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/