server:
    port: 8080
    error:
        include-stacktrace: on_trace_param

spring:
    main:
        web-application-type: reactive
    application:
        name: architecture
    cache:
        type: redis
        redis:
            key-prefix: architecture:cache
    redis:
        cluster:
            nodes:
                - 127.0.0.1:6377
                - 127.0.0.1:6378
                - 127.0.0.1:6379
            maxRedirects: 3
    session:
        store-type: redis
        redis:
            namespace: "{architecture:session}"
            flush-mode: on_save
    mvc:
        log-resolved-exception: false
        locale: zh_CN
    freemarker:
        prefer-file-system-access: false
    jackson:
        serialization:
            write-dates-as-timestamps: true
    security:
        user:
            password: 123
            name: arch
    data:
        mongodb:
            uri: mongodb+srv://learning:WNniz6Mi49Zd8eXx@cluster0-h2zit.mongodb.net/test?retryWrites=true


management:
    server:
        port: 8090
        ssl:
            enabled: false
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true
        health:
            enabled: true
            show-details: always
        info:
            enabled: true
        heapdump:
            enabled: true
        metrics:
            enabled: true
        mappings:
            enabled: true
        loggers:
            enabled: true
