spring:
    application:
        name: web
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/architecture
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            name: primary
            default-transaction-isolation: 2
            maxActive: 20
            initialSize: 10
            minIdle: 10
            maxWait: 5
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: false
            maxPoolPreparedStatementPerConnectionSize: 20
            filters: stat
            connectionProperties: druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=100
    redis:
        cluster:
            nodes:
                - 127.0.0.1:6377
                - 127.0.0.1:6378
                - 127.0.0.1:6379
            maxRedirects: 3
    cache:
        type: redis

mybatis:
    type-aliases-package: com.rainyalley.architecture.entity
    mapper-locations: classpath*:mapper/*Mapper.xml
    check-config-location: false
    executor-type: SIMPLE

swagger:
    title: spring-boot-starter-swagger
    description: Starter for swagger 2.x
    version: 1.3.0.RELEASE
    license: Apache License, Version 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
    termsOfServiceUrl: https://github.com/WakelessDragon/architecture
    contact.name: WakelessDragon
    contact.url: https://github.com/WakelessDragon
    contact.email: sincerebravefight@gmail.com
    base-package: com.rainyalley.architecture.controller
    base-path: /**
    exclude-path: /error, /admin/**

extend:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/architecture
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            name: secondary
            default-transaction-isolation: 1
            maxActive: 20
            initialSize: 10
            minIdle: 10
            maxWait: 5
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: false
            maxPoolPreparedStatementPerConnectionSize: 20
            filters: stat
            connectionProperties: druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=100

server:
    port: 8080

management:
    endpoints:
        enabled-by-default: true
    server:
        port: 8080
    endpoint:
        health:
            show-details: when_authorized
        sessions:
            enabled: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

logging:
    level:
        com.rainyalley.architecture: DEBUG

