spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/architecture
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            name: primary
            default-transaction-isolation: 2
            maxActive: 20
            initialSize: 10
            minIdle: 10
            maxWait: 5
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: false
            maxPoolPreparedStatementPerConnectionSize: 20
            filters: stat
            connectionProperties: druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=100
    redis:
        cluster:
            nodes:
            - 127.0.0.1:6377
            - 127.0.0.1:6378
            - 127.0.0.1:6379
            maxRedirects: 3
    cache:
        type: redis

    batch:
        job:
          enabled: false
        initialize-schema: always
        table-prefix: BATCH_

mybatis:
    type-aliases-package: com.rainyalley.architecture.entity
    mapper-locations: classpath*:mapper/*Mapper.xml
    check-config-location: false
    executor-type: SIMPLE

extend:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/architecture
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            name: secondary
            default-transaction-isolation: 1
            maxActive: 20
            initialSize: 10
            minIdle: 10
            maxWait: 5
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: false
            maxPoolPreparedStatementPerConnectionSize: 20
            filters: stat
            connectionProperties: druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=100


management:
    endpoints:
        enabled-by-default: true
    server:
        port: 8080
    endpoint:
        health:
            show-details: when_authorized
        sessions:
            enabled: true




logging:
    level:
        com.rainyalley.architecture: DEBUG

